### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by NandhiniAnne** [INFO-526-S24/project-final-VizWizards#1]
The following is the peer review of the project proposal by Plot Wizards. The team members that participated in this review are 

- [Sai Navya Reddy Busireddy] - @[navyareddy152]
- [ Nandhini Anne]- @[NandhiniAnne]
- [Anjani Sowmya Bollapragada]- @[asbollapragada]
- [Tejas Bhawari] - @[tezz-us]
- [Srinivasan Poonkundran]- @[kANNISTER]
- [Alexander Berliner] - @[SashaCroatia]
- Mohit Rakesh Taparia- @[mohit-taparia]

- Describe the goal of the project.
  The project conveys the results via a visualization utilizing a R package "shiny" with meteorite landing dataset, and this visualization could assist users explore and evaluate meteorite landings data.

- Describe the data used or collected.
The dataset Meteorite_Landings.csv was obtained from [NASA's Open Data Portal](https://data.nasa.gov/Space-Science/Meteorite-Landings/gh4g-9sfh/about_data). It consists of ten variables, six of which are numerical and four of which are categorical, spread throughout 45716 observations.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Question 1 can be answered by constructing an interactive leaflet map with latitude and longitude data, then calculating the mass of individual impacts to calculate overall mass accumulation across each continent. By combining meteor frequency and mass data, density maps are utilized to illustrate the spatial distribution of meteor mass accumulation per continent, providing insights into global impact patterns.

Question 2 can be answered by making a line graph depicting the frequency of meteor observations per year. The graph will be marked with major historical events pertinent to meteor studies, allowing for an investigation of how these events correspond with variations in meteor observations throughout time. This technique allows for a more contextual understanding of how historical factors have influenced meteor observation and discovery throughout history.

Question3 can be answered by conducting statistical analysis on meteor data and correlate findings with known celestial occurrences like Earth's passages by comets or planets. By identifying patterns such as increased meteor activity during meteor shower events like the Lyrids, which occur due to Earth's traversal of comet debris trails, links between meteor observations and celestial phenomena can be established. By including these discoveries into visualizations, a convincing model of Earth's interactions with other planets in the solar system can be provided.

- Is there anything that is unclear from the proposal?
Everything is clear from the proposal and files are organized properly in the data folder.

- Provide constructive feedback on how the team might be able to improve their project.
The shiny app visualization looks good and has dynamic features which can provide deep insights and it looks the key feature of the project.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are excited to know how insights gained from analyzing meteorite landings data can transcend traditional disciplinary boundaries and contribute to various fields such as astronomy, geology, data science, and even historical studies.

- Provide constructive feedback on any issues with file and/or code organization.
Overall, the proposed repository organization appears well-structured and suitable for managing the project's code, data, and documentation.

- (Optional) Any further comments or feedback?

**Comment by Jasdeep-Singh-Jhajj** [comment]
Thank you Team PlotWizards for the feedback !!
Closing the issue now.
