### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by musketer26** [INFO-526-S24/project-final-VizWizards#2]
The following is the peer review of the project proposal by [DataVista]. The team members that participated in this review are 

- Abhishek Kumar, MS in Data Science -@Abhi291712
- Noureen Mithaigar, MS in information science - @musketer26
- Akash Srinivasan, MS in Data Science- @AkashSrinivasan12
- Lakshmi Neharika Anchula, MS in Data Science-@lakshmineharika
- Gowtham Theeda, MS in Data Science -@gowthamtheeda
- Divya Liladhar Dhole, MS in Data Science -@Divyadhole

- Describe the goal of the project.

The goal is to develop a Shiny app that enables exploration and analysis of meteorite landings data through dynamic visualizations, aiming to understand meteor impact distribution and historical events.

- Describe the data used or collected.

The project utilizes the Meteorite Landings dataset sourced from NASA's Open Data Portal, comprising 10 variables the dataset's scope is restricted to coordinates and timestamps, lacking essential details like atmospheric conditions and meteor impact velocities. Furthermore, it does not encompass all meteor landings, potentially omitting numerous unrecorded instances, thus introducing potential errors and inaccuracies in the findings.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

There is no relation between historical events and meteor sighting " How do historical events relate to the observations and discoveries of meteors?"

- Is there anything that is unclear from the proposal?

There is a discrepancy between the goals and questions with the visualization part (as mentioned there is no analysis in the project ) it is superficial and not detailed, the scope of the project is limited to visualization but not analysis as the focus appears to be primarily on visualization rather than comprehensive data analysis.

- Provide constructive feedback on how the team might be able to improve their project.

The team could consider providing more specific details on the statistical methods planned for identifying trends in meteor data and incorporating potential limitations of the analysis or uncertainties in the findings would strengthen the project.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

 The aspect towards this project that we would like to look forward in the presentation is interactive visualizations developed using Shiny app and how they allow users to explore meteor impact distribution and historical event correlations Effectively.

- Provide constructive feedback on any issues with file and/or code organization.
one constructive feedback could be to consider incorporating more detailed plans for data cleaning and validation procedures to ensure the accuracy and reliability of the analysis results.

- (Optional) Any further comments or feedback?
The project has thoughtful approach to exploring meteorite landings data but it lacks the potential to provide valuable insights into meteor impacts and their relation to historical events and interpretation of meteor activities.

**Comment by Jasdeep-Singh-Jhajj** [comment]
Thank you Team DataVista for your valuable suggestions and improvements, appropriate changes have been made to proposal and modified as per required suggestions.

Closing this Issue now !!
