### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by SashaCroatia** [INFO-526-S24/project-final-VizWizards#6]
The following is the peer review of the Presentation proposal by PlotWizards. The team members that participated in this review are 

Srinivasan Poonkundran- @kANNISTER
Alexander Berliner - @SashaCroatia
Mohit Rakesh Taparia- @mohit-taparia
Sai Navya Reddy Busireddy - @navyareddy152
Nandhini Anne- @NandhiniAnne
Anjani Sowmya Bollapragada- @asbollapragada
Tejas Bhawari - @tezz-us

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, the data is relevant. While there didn't seem to be two overarching questions the team wanted to answer, given the dataset and their intention to provide lots of information to researchers on meteorites, their shiny app answered many smaller questions to provide as much visual information as possible.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes and yes.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Absolutely. They took the time to create two different shiny apps, one to provide categorical information such as when and where a meteorite falls, and another to track the meteorites. Both apps were quite interactive, allowing researchers the freedom to adjust many parameters and to see the trajectory of the meteorites from different angles.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides were basic and didn't commit any organizational blunder. The highlight of the presentation was clearly the final product (the shiny apps) which weren't on the slides.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Overall they presented well and they didn't appear to read off any script, except for a few team members who read off the slides.

**Comment by AgastyaDeshraju** [comment]
Thank you for your feedback!
